/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./../../src/components/SearchMenu/Footer.vue')['default']
    Modal: typeof import('./../../src/components/SearchMenu/Modal.vue')['default']
    Result: typeof import('./../../src/components/SearchMenu/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./../../src/components/Screenfull/index.vue')['default']
    SearchMenu: typeof import('./../../src/components/SearchMenu/index.vue')['default']
  }
}
